config/routes.rb
ResearchMatch::Application.routes.draw do

  get "contact_us/contact", :as => :contact_us
  post "contact_us/send_email", :as => :feedback_email_link

  resources :pictures

  scope '/jobs', :as => :jobs do
    get  '/search' => 'jobs#index', :as => :search
  end

  resources :jobs do
    member do
      get 'activate'
      get 'delete'
      get 'resend_activation_email'
      get 'watch'
      get 'unwatch'
    end
  end

  get '/intro', :to => 'intro#intro'

  get '/team', :to => 'team#team'

  scope :applics do
    get  '/jobs/:job_id/apply' => 'applics#new', :as => :new_job_applic
    post '/jobs/:job_id/apply' => 'applics#create', :as => :create_job_applic
    get  '/jobs/:job_id/applications' => 'applics#index', :as => :list_jobs_applics
    get  '/applications/:id' => 'applics#show', :as => :applic
    get  '/applications/:id/withdraw' => 'applics#destroy', :as => :destroy_applic
    get  '/applications/:id/delete' => 'applics#delete', :as => :delete_applic
    post '/applications/:applic_id' => 'applics#accept'
    post '/applications/:applic_id/unaccept' => 'applics#unaccept'
  end # applics

  resources :documents

  get '/logout' => 'user_sessions#destroy'
  get '/login'  => redirect('/auth/cas')
  get '/auth/:provider/callback' => 'user_sessions#new'

  resources :users
  get  '/dashboard' => 'dashboard#index', :as => :dashboard
  get  '/profile'   => 'users#profile', :as => :profile

  resources :faculties, only: :show
  get  '/' => 'home#index', :as => :home

  resources :orgs, param: :abbr
  post '/orgs/:abbr/curate' => 'orgs#curate', :as => :orgs_curate
  post '/orgs/:abbr/uncurate' => 'orgs#uncurate', :as => :orgs_uncurate

  get '/statistics'      => 'statistics#index', :as => :statistics

  get '/categories/json' => 'categories#json', :as => :categories_json, :defaults => {format: 'json'}
  get '/courses/json' => 'courses#json', :as => :courses_json, :defaults => {format: 'json'}
  get '/proglangs/json' => 'proglangs#json', :as => :proglangs_json, :defaults => {format: 'json'}

  get '/admin' => 'admin#index', :as => :admin
  post '/admin/upload' => 'admin#upload', :as => :admin_upload

  root :to => 'home#index'

  get '/test_error(/:code)' => 'application#test_exception_notification'

  get "*any", via: :all, to: "errors#not_found"

end

app/views/admin/index.html.erb
<h1>Admin Panel</h1>
<div class="admin">
  <h2>Modify User Role</h2>
  <%= form_tag(admin_path, :method => "get") do %>
    <%= label_tag :user_role, "User" %>
    <span class="ui-widget">
      <%= select_tag :user_role, options_for_select([["Select User", nil]] + @non_admins) %>
    </span>
    <%= label_tag :user_role_new, "Role" %>
    <%= select_tag :user_role_new, options_for_select([["Select Role", nil]] + @roles) %>
    <%= submit_tag "Update" %>
  <% end %>
  <br/>
  <h2>Upload User CSV</h2>
  Upload a CSV to update and create authorized users (identified by email).<br/>
  The CSV should have (at minimum) the following columns: name, email, user role. In this case, the header row must be: "name,email,user_role".<br/>
  For creating new users, you will also need to supply a login identifier (e.g. LDAP uses uid). In this case, another column "login_id" will also be needed, and the header row must be: "name,email,user_role,login_id".<br/>
  User role 0 corresponds to an undergraduate student, 1 to a graduate student, 2 to a faculty member, 3 to an admin.<br/><br/>
  <%= form_tag(admin_upload_path, :multipart => true) do %>
    <%= file_field_tag 'user_csv', :accept => 'text/csv' %>
    <%= submit_tag 'Upload' %>
  <% end %>
</div>