config/routes.rb
ResearchMatch::Application.routes.draw do

  get "contact_us/contact", :as => :contact_us
  post "contact_us/send_email", :as => :feedback_email_link

  resources :pictures

  scope '/jobs', :as => :jobs do
    get  '/search' => 'jobs#index', :as => :search
  end

  resources :jobs do
    member do
      get 'activate'
      get 'delete'
      get 'resend_activation_email'
      get 'watch'
      get 'unwatch'
    end
  end

  get '/intro', :to => 'intro#intro'

  get '/team', :to => 'team#team'

  scope :applics do
    get  '/jobs/:job_id/apply' => 'applics#new', :as => :new_job_applic
    post '/jobs/:job_id/apply' => 'applics#create', :as => :create_job_applic
    get  '/jobs/:job_id/applications' => 'applics#index', :as => :list_jobs_applics
    get  '/applications/:id' => 'applics#show', :as => :applic
    get  '/applications/:id/withdraw' => 'applics#destroy', :as => :destroy_applic
    get  '/applications/:id/delete' => 'applics#delete', :as => :delete_applic
    post '/applications/:applic_id' => 'applics#accept'
    post '/applications/:applic_id/unaccept' => 'applics#unaccept'
  end # applics

  resources :documents

  get '/logout' => 'user_sessions#destroy'
  get '/login'  => redirect('/auth/cas')
  get '/auth/:provider/callback' => 'user_sessions#new'

  resources :users
  get  '/dashboard' => 'dashboard#index', :as => :dashboard
  get  '/profile'   => 'users#profile', :as => :profile

  resources :faculties, only: :show
  get  '/' => 'home#index', :as => :home

  resources :orgs, param: :abbr
  post '/orgs/:abbr/curate' => 'orgs#curate', :as => :orgs_curate
  post '/orgs/:abbr/uncurate' => 'orgs#uncurate', :as => :orgs_uncurate

  get '/statistics'      => 'statistics#index', :as => :statistics

  get '/categories/json' => 'categories#json', :as => :categories_json, :defaults => {format: 'json'}
  get '/courses/json' => 'courses#json', :as => :courses_json, :defaults => {format: 'json'}
  get '/proglangs/json' => 'proglangs#json', :as => :proglangs_json, :defaults => {format: 'json'}

  get '/admin' => 'admin#index', :as => :admin
  post '/admin/upload' => 'admin#upload', :as => :admin_upload

  root :to => 'home#index'

  get '/test_error(/:code)' => 'application#test_exception_notification'

  get "*any", via: :all, to: "errors#not_found"

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@departments = Department.all
	end
	
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
- content_for :title, "Welcome"
#home-container
  .main-top-bg-container
    .main-top-bg
  .main-top
    .main-title
      .text-info-large
        %span
          Research made simple
    .main-top-info
      .text-info-small
        Search and filter over
        %span= Job.count
        exciting projects.
        Joining a project has never been easier!
        
    %span.main-icons-container
      .main-icons
  .main-btn-container.clearfix
    - if @current_user.present?
      = link_to "EXPLORE", jobs_path, class: "btn btn-cal btn-landing"
    - else
      = link_to "EXPLORE", login_path, class: "btn btn-cal btn-landing"
  .row.main-bottom
    .col-md-4.col-landing-card
      .smartmatch.landing-card
        .title
          BROWSE
        .details
          We've made it easy for you to find your perfect project.
    .col-md-4.col-landing-card
      .smartmatch.landing-card
        .title
          EASY APPLYING
        .details
          No need to fill out endless forms.
          Write what's relevant, and we'll take care of the rest.
    .col-md-4.col-landing-card
      .smartmatch.landing-card
        .title
          SMARTMATCH
        .details
          Can't find a project you like?
          We'll let you know when a new project matches your interests.
  .heightfix