config/routes.rb
ResearchMatch::Application.routes.draw do

  get "contact_us/contact", :as => :contact_us
  post "contact_us/send_email", :as => :feedback_email_link

  resources :pictures

  scope '/jobs', :as => :jobs do
    get  '/search' => 'jobs#index', :as => :search
  end

  resources :jobs do
    member do
      get 'activate'
      get 'delete'
      get 'resend_activation_email'
      get 'watch'
      get 'unwatch'
    end
  end

  get '/intro', :to => 'intro#intro'

  get '/team', :to => 'team#team'

  scope :applics do
    get  '/jobs/:job_id/apply' => 'applics#new', :as => :new_job_applic
    post '/jobs/:job_id/apply' => 'applics#create', :as => :create_job_applic
    get  '/jobs/:job_id/applications' => 'applics#index', :as => :list_jobs_applics
    get  '/applications/:id' => 'applics#show', :as => :applic
    get  '/applications/:id/withdraw' => 'applics#destroy', :as => :destroy_applic
    get  '/applications/:id/delete' => 'applics#delete', :as => :delete_applic
    post '/applications/:applic_id' => 'applics#accept'
    post '/applications/:applic_id/unaccept' => 'applics#unaccept'
  end # applics

  resources :documents

  get '/logout' => 'user_sessions#destroy'
  get '/login'  => redirect('/auth/cas')
  get '/auth/:provider/callback' => 'user_sessions#new'

  resources :users
  get  '/dashboard' => 'dashboard#index', :as => :dashboard
  get  '/profile'   => 'users#profile', :as => :profile

  resources :faculties, only: :show
  get  '/' => 'home#index', :as => :home

  resources :orgs, param: :abbr
  post '/orgs/:abbr/curate' => 'orgs#curate', :as => :orgs_curate
  post '/orgs/:abbr/uncurate' => 'orgs#uncurate', :as => :orgs_uncurate

  get '/statistics'      => 'statistics#index', :as => :statistics

  get '/categories/json' => 'categories#json', :as => :categories_json, :defaults => {format: 'json'}
  get '/courses/json' => 'courses#json', :as => :courses_json, :defaults => {format: 'json'}
  get '/proglangs/json' => 'proglangs#json', :as => :proglangs_json, :defaults => {format: 'json'}

  get '/admin' => 'admin#index', :as => :admin
  post '/admin/upload' => 'admin#upload', :as => :admin_upload

  root :to => 'home#index'

  get '/test_error(/:code)' => 'application#test_exception_notification'

  get "*any", via: :all, to: "errors#not_found"

end

app/models/applic.rb
# == Schema Information
#
# Table name: applics
#
#  id            :integer          not null, primary key
#  job_id        :integer
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  message       :text
#  resume_id     :integer
#  transcript_id :integer
#  status        :string(255)      default("undecided")
#  applied       :boolean
#

class Applic < ActiveRecord::Base


  belongs_to :job
  belongs_to :user
  validates_presence_of   :message
  validates_length_of     :message, :minimum => 1, :too_short => 'Please enter a message to the faculty sponsor of this listing.'
  validates_length_of     :message, :maximum => 65536, :too_long => 'Please enter a message to the faculty sponsor of this listing that is shorter than 65536 characters.'

  # Uniq'd list of emails of all [sponsors, poster] who want to receive notifications for this applic
  def subscriber_emails
    # TODO: for now, just email the poster
    job.user.email

    # TODO: add preferences to these people
    # TODO: condense faculty -> users
##    emales = job.faculties.collect(&:email)
##    emales << user.email
##    emales
  end

  def unread?
    return false
  end

end

app/controllers/applics_controller.rb
class ApplicsController < ApplicationController
  include CASControllerIncludes
  before_filter :rm_login_required

  before_filter :find_objects

  # These filters verify that @current_user has the right permissions
  before_filter :verify_applic_ownership, :only => [:destroy]
    # only applicant can withdraw
  before_filter :verify_applic_admin,     :only => [:show, :resume, :transcript]
    # applicant, job admin can view applic
  before_filter :verify_job_ownership,    :only => [:index, :delete]
    # show applics only if can admin
  before_filter :verify_job_unapplied,    :only => [:create]
    # don't allow multiple applications

  before_filter :job_accessible, :only => [ :new, :create, :index ]

  # Prohibits a user from applying to his/her own job
  before_filter :watch_apply_ok_for_job, :only => [ :new, :create ]

  protected
  def find_objects
    @applic = Applic.find(params[:id])  unless params[:id].blank?
    @job    = Job.find(params[:job_id]) unless params[:job_id].blank?
  end

  def verify_job_unapplied
    existing = Applic.where({:user_id => @current_user, :job_id => @job.id, :applied => true}).first
    if existing
      flash[:error] = "Whoa, slow down! You've already applied for this job. "
      flash[:error] << "If you'd like to update your application, please "
      flash[:error] << "withdraw your existing one first."
      redirect_to(url_for(existing))
      return false
    else
      return true
    end
  end

  def verify_applic_ownership
    a = @applic #Applic.find(params[:id])
    return if redirect_if(a.nil?, "Couldn't find that application.", jobs_path)
    return if redirect_if(a.user != @current_user,
      'Only the original applicant can withdraw an application.', job_path(a.job))
  end

  def verify_applic_admin
    a = @applic #Applic.find(params[:id])
    return if redirect_if(a.nil?, "Couldn't find that application.", jobs_path)
    return if redirect_if(a.user == @current_user || !a.job.can_admin?(@current_user),
      'You are not authorized to view that application.', job_path(a.job))
  end

  def verify_job_ownership
    j = @job #Job.find(params[:job_id])
    a = @applic
    return if redirect_if(j.nil? && a.nil?, "Couldn't find that job.", jobs_path)
    if !j.nil?
      return if redirect_if(! j.can_admin?(@current_user),
        "You are not authorized to view the applications for this job.",
        job_path(j))
    else
      return if redirect_if(! a.job.can_admin?(@current_user),
        "You are not authorized to view the applications for this job.",
        job_path(a.job))
    end
  end

  def serve_document(type)
    return unless [:resume, :transcript].include?(type)
    @doc = @applic.send(type)
    return if redirect_if(@doc.nil?,
      "There was an error retrieving the requested document.",
      applic_path(@applic))
    send_file @doc.public_filename, :type => @doc.content_type
  end

  public
  def resume
    serve_document(:resume)
  end

  def transcript
    serve_document(:transcript)
  end

  def show
    @applic = Applic.find(params[:id])
    @status = @applic.status.nil? ? 'Undecided' : @applic.status.capitalize

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @applic }
    end
  end

  def new
    if verify_job_unapplied
      @applic = Applic.find_or_initialize_by({:user => @current_user, :job => @job})
    else
      redirect_to(url_for(@job))
    end

  end

  # the action for actually applying.
  def create
    @applic = Applic.where({:user_id => @current_user.id, :job_id => @job.id}).first
    if @applic
      @applic.message = params[:applic][:message]
      @applic.answer_1 = params[:applic][:answer_1]
      @applic.answer_2 = params[:applic][:answer_2]
      @applic.answer_3 = params[:applic][:answer_3]
    else
      @applic = Applic.new({:user_id => @current_user.id, :job_id => @job.id}.update(params[:applic]))
    end

    if (@job.question_1 != nil && @job.question_1 != "" && (@applic.answer_1 == nil || @applic.answer_1 == "")) ||
       (@job.question_2 != nil && @job.question_2 != "" && (@applic.answer_2 == nil || @applic.answer_2 == "")) ||
       (@job.question_3 != nil && @job.question_3 != "" && (@applic.answer_3 == nil || @applic.answer_3 == ""))
       flash[:error] = "Could not apply to position. Make sure you've " +
                        "answered faculty questions"
      render'new'
      return
    end

    @applic.resume_id = @current_user.resume.id if params[:include_resume] &&
      @current_user.resume.present?
    @applic.transcript_id = @current_user.transcript.id if
      params[:include_transcript] && @current_user.transcript.present?
    # submit an application
    if params[:commit] == 'Submit'
      # update an existing application
      @applic.applied = true
      if @applic.save
        # Validate and send emails
        user_email = @job.user.email
        contact_email = @job.contacter.email

        if !contact_email.empty?
          JobMailer.deliver_applic_email(@applic, contact_email).deliver
          flash[:notice] = 'Application sent. Time to cross your fingers and wait for a reply!'
        else
          flash[:error] = "Looks like the job's contacts have invalid emails.
                           Please contact us for further support.
                           Your application has been submitted."
        end
        redirect_to job_path(@job)
      else
        flash[:error] = "Could not apply to position. Make sure you've " +
                        "written a message to the faculty sponsor!"
        render 'new'
      end

    else # save an application
      @applic.applied = false

      if @applic.save
        flash[:notice] = 'Application saved. You can come back later and complete your application!'
        redirect_to job_path(@job)
      else
        flash[:error] = "Could not save application. Make sure you've " +
                        "written a message to the faculty sponsor!"
        render 'new'
      end
    end
  end

  def delete
    applic = Applic.find_by_id(params[:id])
    job_id = applic.job_id.to_s
    if !applic.nil?
      applic.status = "not accepted"
      applic.save
      flash[:notice] = "Applicants %s was rejected/removed" % applic.user.name
    end
    redirect_to('/jobs/%s' % job_id)
  end

  # withdraw from an application (destroy the applic)
  def destroy
    applic = Applic.find(:job_id=>params[:id])
    if !applic.nil? && applic.user == @current_user
      respond_to do |format|
        if applic.destroy
          flash[:error] = "Withdrew your application successfully. "
          flash[:error] << "Keep in mind that your initial application "
          flash[:error] << "email has already been sent."
          format.html { redirect_to(:controller=>:jobs, :action=>:index) }
        else
          flash[:error] = "Couldn't withdraw your application. "
          flash[:error] << "Please try again, or contact support."
          format.html { redirect_to(:controller=>:dashboard) }
        end
      end
    else
      flash[:error] = "Error: Couldn't find that application."
      redirect_to(:controller=>:dashboard)
    end
  end

  def accept
    applic = Applic.find_by_id(params[:applic_id])
    if !applic.nil?
      applic.status = "accepted"
      applic.save
      flash[:notice] = "Applicant %s was accepted" % applic.user.name
    end
    redirect_to('/applics/applications/%s' % applic.id)
  end

  def unaccept
    applic = Applic.find_by_id(params[:applic_id])
    job_id = applic.job_id.to_s
    if !applic.nil?
      applic.destroy
      flash[:notice] = "Accepted hire %s was removed" % applic.user.name
    end
    redirect_to job_path(job_id)
  end

  def index
    flash[:notice] = "Application listing not implemented yet."
    redirect_to job_path(@job)
  end
end

app/views/applics/_applic.html.erb
<% job = applic.job -%>
<% if job!=nil -%>
<tr class="job_<%= cycle('even', 'odd') %>">
  <td>
    <% if mine -%>
      <%= applic.updated_at.strftime('%B %d, %Y') %>
    <% else -%>
      <%= link_to applic.updated_at.strftime('%B %d, %Y'), applic_path(applic) -%>
    <% end %>
  </td>
  <td><%= link_to job.title, job_path(job) %></td>
  <td>
    <% if mine -%>
      <%= job.user.nil? ? 'None' + (applic.unread? ? '[updated]' : '') : link_to(job.contacter.name, user_path(job.primary_contact_id)) %>
    <% else -%>
      <%= link_to applic.user.name, applic_path(applic) -%>
    <% end %>
  </td>
  <td>
  <% if mine && !applic.applied -%>
    <% if job.open? -%>
    <%= link_to "Incomplete [Continue]", new_job_applic_path(job) %>
    <% else -%>
    Incomplete, Closed
    <% end -%>
  <% elsif applic.status -%>
    <%= applic.status.capitalize -%>
  <% else -%><!-- TODO:add read -->
    Undecided
  <% end %>
  </td>


</tr>
<% end -%>

app/views/applics/new.html.haml
- content_for :title, "Apply for Listing"
.container
  .card
    .row
      .large-10.col-sm-12.columns
        %h1="Apply for Project - #{@job.title}"
        %p
          To apply for the following project, please enter a message to send to the faculty #{'sponsor'.pluralize_for @job.faculties.count} and review the info that will be provided.
        = form_for(@applic, :url=>create_job_applic_path(@applic.job.id, @applic.id), :method => :post ) do |f|
          = render(:partial => "jobs/job_snippet", :job => @job )
          %strong Message to faculty
          = f.text_area :message, :rows=>10, :value => @applic.message, :class => "form-control"
          - if (@job.question_1 != nil && @job.question_1 != "") || (@job.question_2 != nil && @job.question_2 != "")|| (@job.question_3 != nil  && @job.question_3 != "")
            %h2 
              Faculty Questions
            %p
              Please answer the following questions
            - if @job.question_1 != nil && @job.question_1 != ""
              %strong #{@job.question_1}
              = f.text_area :answer_1, :rows=>3, :value => @applic.answer_1, :class => "form-control"
            - if @job.question_2 != nil && @job.question_2 != ""
              %strong #{@job.question_2}
              = f.text_area :answer_2, :rows=>3, :value => @applic.answer_2, :class => "form-control"
            - if @job.question_3 != nil  && @job.question_3 != ""
              %strong #{@job.question_3}
              = f.text_area :answer_3, :rows=>3, :value => @applic.answer_3, :class => "form-control"

          %hr
          %h2 Application
          %p
            By applying for this listing, you grant the faculty #{'sponsor'.pluralize_for @job.faculties.count}
            (#{@job.faculties.collect(&:name).join(', ')}) access to view #{link_to 'your profile', profile_path, :target => '_blank'} and any information you've entered there.
            Please review the following information before submitting. A copy will be emailed to the faculty
            \#{'sponsor'.pluralize_for @job.faculties.count}.
          = render 'users/applic_info', :format => :html, :user => @current_user
          = f.submit 'Submit', class: "btn btn-primary"
          = f.submit 'Save', class: "btn btn-info"
          %input{:onclick => "location.href='#{url_for(@job)}'", :type => "button", :value => "Cancel", :class => "btn btn-danger"}/
        = link_to raw('« Back to listings'), jobs_path

app/views/applics/show.html.haml
- content_for :title, "Application Details"
- @job = @applic.job
.container#applic_show_main
  %h1= "Application - #{@applic.job.title}"
  .card
    %h2 Application Info
    %dl.dl-horizontal
      %dt Applicant
      %dd= @applic.user.name

      %dt Status
      %dd= @status

      %dt Date applied
      %dd= @applic.created_at.getlocal.pp

      %dt Message
      %dd= @applic.message
    


    %h2 Applicant Profile
    = render 'users/applic_info', :user => @applic.user

    - if (@job.question_1 != nil && @job.question_1 != "") || (@job.question_2 != nil && @job.question_2 != "")|| (@job.question_3 != nil  && @job.question_3 != "")
      %h2 Faculty Questions 
      - if @job.question_1 != nil && @job.question_1 != ""
        %dt #{@job.question_1}
        %dd= @applic.answer_1 
      - if @job.question_2 != nil && @job.question_2 != ""
        %dt #{@job.question_2}
        %dd= @applic.answer_2
      - if @job.question_3 != nil && @job.question_3 != ""
        %dt #{@job.question_3}
        %dd= @applic.answer_3

    .row
      - if @applic.status != "accepted"
        .col-md-2
          = form_tag('/applics/applications/%s' % @applic.id, :method => "post") do
            = submit_tag "Accept", class: "btn btn-success"
        .col-md-1
          = form_tag('/applics/applications/%s/delete' % @applic.id, :method => "get") do
            = submit_tag "Reject", class: "btn btn-danger"
      - if @applic.status == "accepted"
        .col-md-1
          = form_tag('/applics/applications/%s/unaccept' % @applic.id, :method => "post") do
            = submit_tag "Unhire Accepted Applicant", class: "btn btn-warning"
    .row
      .col-md-1
        = link_to 'Return to Project', '/jobs/%s' % @applic.job.id, class: "btn btn-primary"